Revert "qtlocation: enable geoservices_mapboxgl"
This reverts commit aacacea2bbb1ef0145db907789a451eeb9789b89.

Fails as shown in:
http://errors.yoctoproject.org/Errors/Details/852834/

In file included from TOPDIR/tmp/work/core2-64-oe-linux/qtlocation/5.15.16+git/recipe-sysroot/usr/include/unicode/ubidi.h:26,
                 from TOPDIR/tmp/work/core2-64-oe-linux/qtlocation/5.15.16+git/git/src/3rdparty/mapbox-gl-native/platform/default/bidi.cpp:4:
TOPDIR/tmp/work/core2-64-oe-linux/qtlocation/5.15.16+git/recipe-sysroot/usr/include/unicode/localpointer.h:561:26: error: 'auto' parameter not permitted in this context
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
TOPDIR/tmp/work/core2-64-oe-linux/qtlocation/5.15.16+git/recipe-sysroot/usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid [-Wtemplate-body]
  573 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
      |                                                                            ^
TOPDIR/tmp/work/core2-64-oe-linux/qtlocation/5.15.16+git/recipe-sysroot/usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid [-Wtemplate-body]
  583 |     LocalOpenPointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {
      |                                                                              ^
TOPDIR/tmp/work/core2-64-oe-linux/qtlocation/5.15.16+git/recipe-sysroot/usr/include/unicode/localpointer.h:599:59: error: template argument 2 is invalid [-Wtemplate-body]
  599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^